// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Product struct {
	ID        uuid.UUID
	Name      string
	Price     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Email          string
	Hashedpassword string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Role           string
}
