// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProductsFromRequest = `-- name: CreateProductsFromRequest :one
INSERT INTO products (id, name, price, created_at, updated_at, posted_by)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    $3

)
RETURNING id, name, price, created_at, updated_at, posted_by
`

type CreateProductsFromRequestParams struct {
	Name     string
	Price    string
	PostedBy uuid.UUID
}

func (q *Queries) CreateProductsFromRequest(ctx context.Context, arg CreateProductsFromRequestParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProductsFromRequest, arg.Name, arg.Price, arg.PostedBy)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostedBy,
	)
	return i, err
}
